/**
 * @file: adapters/ProjectExporter.ts
 * @description: 项目导出功能，支持 ZIP 下载和 JSON 导出
 * @author: YanYuCloudCube Team <admin@0379.email>
 * @version: v1.0.0
 * @created: 2026-03-08
 * @updated: 2026-03-14
 * @status: dev
 * @license: MIT
 * @copyright: Copyright (c) 2026 YanYuCloudCube Team
 * @tags: adapters,export,zip,json
 */

import JSZip from "jszip";
import { saveAs } from "file-saver";

// ── 类型 ──

export interface ExportOptions {
  projectName: string;
  includePackageJson?: boolean;
  includeTsConfig?: boolean;
  includeViteConfig?: boolean;
  includeReadme?: boolean;
}

// ── 生成默认配置文件 ──

function generatePackageJson(name: string): string {
  return JSON.stringify(
    {
      name: name.toLowerCase().replace(/\s+/g, "-"),
      private: true,
      version: "0.1.0",
      type: "module",
      scripts: {
        dev: "vite",
        build: "tsc && vite build",
        preview: "vite preview",
      },
      dependencies: {
        react: "^18.3.1",
        "react-dom": "^18.3.1",
      },
      devDependencies: {
        "@types/react": "^18.3.0",
        "@types/react-dom": "^18.3.0",
        "@vitejs/plugin-react": "^4.3.0",
        typescript: "^5.5.0",
        vite: "^6.0.0",
        tailwindcss: "^4.0.0",
        "@tailwindcss/vite": "^4.0.0",
      },
    },
    null,
    2,
  );
}

function generateTsConfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2020",
        useDefineForClassFields: true,
        lib: ["ES2020", "DOM", "DOM.Iterable"],
        module: "ESNext",
        skipLibCheck: true,
        moduleResolution: "bundler",
        allowImportingTsExtensions: true,
        isolatedModules: true,
        moduleDetection: "force",
        noEmit: true,
        jsx: "react-jsx",
        strict: true,
        noUnusedLocals: true,
        noUnusedParameters: true,
        noFallthroughCasesInSwitch: true,
        noUncheckedSideEffectImports: true,
      },
      include: ["src"],
    },
    null,
    2,
  );
}

function generateViteConfig(): string {
  return `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'

export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
  ],
})
`;
}

function generateReadme(name: string): string {
  return `# ${name}

Generated by YYC³ Family AI

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

## Tech Stack

- React 18 + TypeScript
- Vite
- Tailwind CSS 4

---

*Exported on ${new Date().toLocaleDateString("zh-CN")}*
`;
}

// ── ZIP 导出 ──

export async function exportAsZip(
  files: Record<string, string>,
  options: ExportOptions,
): Promise<void> {
  const zip = new JSZip();

  // Add project files
  for (const [path, content] of Object.entries(files)) {
    zip.file(path, content);
  }

  // Add config files if requested
  if (options.includePackageJson !== false && !files["package.json"]) {
    zip.file("package.json", generatePackageJson(options.projectName));
  }

  if (options.includeTsConfig !== false && !files["tsconfig.json"]) {
    zip.file("tsconfig.json", generateTsConfig());
  }

  if (options.includeViteConfig !== false && !files["vite.config.ts"]) {
    zip.file("vite.config.ts", generateViteConfig());
  }

  if (options.includeReadme !== false && !files["README.md"]) {
    zip.file("README.md", generateReadme(options.projectName));
  }

  // Generate and download
  const blob = await zip.generateAsync({
    type: "blob",
    compression: "DEFLATE",
    compressionOptions: { level: 6 },
  });

  const fileName = `${options.projectName.replace(/\s+/g, "-").toLowerCase()}-${formatDate()}.zip`;
  saveAs(blob, fileName);
}

// ── JSON 导出 ──

export function exportAsJson(
  files: Record<string, string>,
  options: ExportOptions,
): void {
  const exportData = {
    projectName: options.projectName,
    exportedAt: new Date().toISOString(),
    generator: "YYC³ Family AI",
    fileCount: Object.keys(files).length,
    files,
  };

  const blob = new Blob([JSON.stringify(exportData, null, 2)], {
    type: "application/json",
  });

  const fileName = `${options.projectName.replace(/\s+/g, "-").toLowerCase()}-${formatDate()}.json`;
  saveAs(blob, fileName);
}

// ── JSON 导入 ──

export interface ImportResult {
  success: boolean;
  projectName: string;
  files: Record<string, string>;
  fileCount: number;
  error?: string;
}

export function importFromJson(jsonString: string): ImportResult {
  try {
    const data = JSON.parse(jsonString);

    if (!data.files || typeof data.files !== "object") {
      return {
        success: false,
        projectName: "",
        files: {},
        fileCount: 0,
        error: "无效的项目文件格式：缺少 files 字段",
      };
    }

    return {
      success: true,
      projectName: data.projectName || "Imported Project",
      files: data.files,
      fileCount: Object.keys(data.files).length,
    };
  } catch (err) {
    return {
      success: false,
      projectName: "",
      files: {},
      fileCount: 0,
      error: `JSON 解析失败: ${err instanceof Error ? err.message : String(err)}`,
    };
  }
}

// ── ZIP 导入 ──

export async function importFromZip(file: File): Promise<ImportResult> {
  try {
    const zip = await JSZip.loadAsync(file);
    const files: Record<string, string> = {};

    const entries = Object.entries(zip.files);

    for (const [path, zipEntry] of entries) {
      if (zipEntry.dir) continue;

      // Skip hidden files and node_modules
      if (path.startsWith(".") || path.includes("node_modules/")) continue;

      // Only import text files
      const ext = path.split(".").pop()?.toLowerCase();
      const textExts = [
        "ts",
        "tsx",
        "js",
        "jsx",
        "css",
        "scss",
        "html",
        "json",
        "md",
        "txt",
        "yaml",
        "yml",
        "toml",
        "env",
        "gitignore",
      ];
      if (ext && textExts.includes(ext)) {
        const content = await zipEntry.async("string");
        files[path] = content;
      }
    }

    // Try to extract project name from package.json
    let projectName = file.name.replace(/\.zip$/i, "");
    if (files["package.json"]) {
      try {
        const pkg = JSON.parse(files["package.json"]);
        if (pkg.name) projectName = pkg.name;
      } catch {
        /* ignore */
      }
    }

    return {
      success: true,
      projectName,
      files,
      fileCount: Object.keys(files).length,
    };
  } catch (err) {
    return {
      success: false,
      projectName: "",
      files: {},
      fileCount: 0,
      error: `ZIP 解析失败: ${err instanceof Error ? err.message : String(err)}`,
    };
  }
}

// ── 辅助 ──

function formatDate(): string {
  return new Date().toISOString().slice(0, 10);
}

// ── 项目统计 ──

export function getProjectStats(files: Record<string, string>): {
  fileCount: number;
  totalSize: number;
  totalSizeFormatted: string;
  byExtension: Record<string, number>;
  largestFile: { path: string; size: number } | null;
} {
  const byExtension: Record<string, number> = {};
  let totalSize = 0;
  let largestFile: { path: string; size: number } | null = null;

  for (const [path, content] of Object.entries(files)) {
    const size = new Blob([content]).size;
    totalSize += size;

    const ext = path.split(".").pop() || "other";
    byExtension[ext] = (byExtension[ext] || 0) + 1;

    if (!largestFile || size > largestFile.size) {
      largestFile = { path, size };
    }
  }

  return {
    fileCount: Object.keys(files).length,
    totalSize,
    totalSizeFormatted: formatBytes(totalSize),
    byExtension,
    largestFile,
  };
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}
